apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-asvg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-asvg
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-asvg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-asvg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-asvg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mvfq-tenant/rhtap-demo-app/hacbs-test-project-asvg@sha256:9a6807bf30bd7354646f25dc34a1c00cb89b54b8ff8984438049e9c69f0e2b78
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
